### ISSUE TITLE
When balance runs out, go back to paywall page.

### ISSUE THREAD

**Issue by criticaltv** [videoDAC/apps#11]
Currently, when the app wallet runs out of money, it turns everything off. TV off. App gone.

Perhaps it might be better to keep the viewer in the app, so that they can start watching again more easily.

If they're watching live, then they want to get back to the live action as soon as is possible... so show them the information they need to know, in order to solve their problem.

**Comment by mul1sh** [comment]
Done :)

**Comment by criticaltv** [comment]
I haven't been able to verify this as being closed. Reopening so we can track it...

**Comment by criticaltv** [comment]
Closed
