### ISSUE TITLE
Please remove player controls

### ISSUE THREAD

**Issue by criticaltv** [videoDAC/apps#12]
Please can the play button bar be removed altogether?

Let's completely strip it out.

It's not necessary.

It plays live.

No pause, no rewind, no fast forward.

No "skip to next" (there is no next). No "skip to previous" (there is no previous)

Only the present moment. The here and now.

So, the play button bar, as shown in the screenshot below, should be removed completely.

![Screenshot_20200124-021315](https://user-images.githubusercontent.com/59374467/73038773-f0b7b380-3e53-11ea-9ffc-62d4c511aaa1.png)

**Comment by mul1sh** [comment]
Done :)
