### ISSUE TITLE
Web3 Integration

### ISSUE THREAD

**Issue by mul1sh** [videoDAC/apps#3]
Integrate the app with web3 capabilities so that users can be able to do the following,

- Create new wallets
- Import existing wallets into the app
- Safely export and backup wallets
- Pay for the livestreams as described here https://github.com/videoDAC/infinite-digital-stage/issues/3

**Comment by criticaltv** [comment]
I like it. Which micropayment platform to use?

**Comment by criticaltv** [comment]
Here is some wisdom from @ArjunBhuptani from @ConnextProject:

![Screenshot_20200112-011831](https://user-images.githubusercontent.com/59374467/72212288-945ea680-34d9-11ea-85f8-e671c3f5170c.png)

Links are:
https://github.com/ConnextProject/indra/blob/staging/README.md
http://docs.connext.network/en/latest/userDocumentation/quickStart.html

**Comment by mul1sh** [comment]
1st iteration of this functionality has been implemented.
