### ISSUE TITLE
Suggested feature: "turn TV off" copies the "Credits Wallet Address" to your clipboard

### ISSUE THREAD

**Issue by criticaltv** [videoDAC/apps#6]
When a user closes the app, the app should publish "Credits Wallet Address" to the user's clipboard.

This may be perhaps at this screen, when a user needs to know where to send viewing credits:

![image](https://user-images.githubusercontent.com/59374467/72671745-1a856a80-3a4f-11ea-9109-b584fde03bcd.png)

It may also be when a viewer turns the stream off, and with their address on clipboard, they can check their balance easily using something like Etherscan.

![Screenshot from 2020-01-05 19-16-27](https://user-images.githubusercontent.com/59374467/72671773-b0b99080-3a4f-11ea-8faf-b256dcc7dd3f.png)

**Comment by criticaltv** [comment]
The user should also be notified that the address is on their clipboard. e.g. display some text like:

"Address copied to clipboard 0xdac817294c0c87ca4fa1895ef4b972eade99f2fd"

**Comment by mul1sh** [comment]
Fixed
